[project]
name = "hostfocuser160"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "PyQt6>=6.10.2",
    "pyqt6_sip>=13.11.0",
    "pythonping>=1.1.4",
    "pyzmq>=27.1.0",
    "scipy>=1.17.0",
    "toml>=0.10.2",
    "icmplib==3.0.4",
    "pyModbusTCP>=0.3.0"
]
