title = "Focuser160MQ"

[General]
name = "Focuser160"
version = "1.0.0"
description = "Interface for Perkin-Elmer Focuser"
startup = false
pub_interval = 1

[Device]
absolute = true
device_name = "2ndMirror"
deviceID = "3285e9af-8d1d-4f9d-b368-d129d8e9a24b"
ip_160 = "192.168.0.250"
ip_iag = "192.168.60.120"
router_ip = "192.168.0.1"
device_port = 5001
encoder2microns = 42.2047244
max_increment = 0
tempcompavailable = false
temp_comp = false
speed_security = 215000
speedFactor = 428
step_size = 0
device_ip = "192.168.0.250"
backlash = 4
max_pos = 45
park_pos = 15
normal_speed = 3400
low_speed = 1700
max_step = 9
max_speed = 4400
acceleration = 9
deceleration = 8
idle_current = 14
run_current = 19
acc_current = 41

[Network]
server_ip = "*"
port_pub = 7003
port_rep = 7004
sub_mask = "255.255.255.0"
gateway_ip = "192.168.0.1"
pub_port = 7003
rep_port = 7004

[Logging]
log_level = "INFO"
log_to_stdout = false
log_max_size_mb = 10
log_num_keep = 10
