title = "FocuserPE160"

[General]
name = "PE 160 Focuser"
version = "1.0.0"
date = "02/06/2026"
description = "Interface for Perkin-Elmer Focuser"
startup = true

[Device]
absolute = true
device_name = "2ndMirror"
deviceID = "3285e9af-8d1d-4f9d-b368-d129d8e9a24b"
device_ip = "192.168.0.250"
device_port = 5001
max_increment = 0
tempcompavailable = false
temp_comp = false
speed_security = 215000
speedFactor = 1
step_size = 0
backlash = 2
max_pos = 50
park_pos = 15
normal_speed = 210
low_speed = 1000
max_speed = 3000
acceleration = 9
deceleration = 8
idle_current = 14
run_current = 19
acc_current = 41
step_offset = 0
cmd_timeout = 5
encoder2microns = 42.2047244
steps2encoder = 20
microns2rps = 0.0025
clp_auto_restart = true
motor_auto_restart = true
tcp_retransmission_timeout = 30
tcp_com_cycle_timeout = 5
tcp_modbus_timeout = 1000
tcp_keep_alive_timeout = 30

[Network]
server_ip = "*"
port_pub = 7003
port_rep = 7004
sub_mask = "255.255.255.0"
gateway_ip = "192.168.0.1"
clp_ip = "127.0.0.1"
pub_port = 7003
rep_port = 7004
pub_interval = 0.2
handshake_timeout = 5

[Logging]
log_level = "INFO"
log_to_stdout = false
log_max_size_mb = 10
log_num_keep = 10
