title = "FocuserIAG"

[General]
name = "FocuserIAG"
version = "1.0.0"
description = "Interface for IAG Focuser"
startup = false

[Device]
absolute = true
device_name = "2ndMirror"
deviceID = "3285e9af-8d1d-4f9d-b368-d129d8e9a24b"
device_ip = "0.0.0.0"
device_port = 5005
encoder2microns = 42.2047244
max_increment = 0
tempcompavailable = false
temp_comp = false
speed_security = 215000
speedFactor = 428
step_size = 0
backlash = 18
max_pos = 12583
park_pos = 6000
normal_speed = 190
low_speed = 25
max_step = 9
max_speed = 250
acceleration = 5
deceleration = 20
idle_current = 8
run_current = 120
acc_current = 200
cmd_timeout = 7

[Network]
server_ip = "*"
port_pub = 7003
port_rep = 7004
sub_mask = "255.255.255.0"
gateway_ip = "192.168.50.1"
pub_interval = 1
write_timeout = 3

[Logging]
log_level = "INFO"
log_to_stdout = false
log_max_size_mb = 10
log_num_keep = 10
