from collections import namedtuple


# Coils_regs = namedtuple('Coils_regs',
#                         ['RX_ALM', 
#                          'TX_CGT_B',
#                          'TX_CGT_C',
#                          ])

# coils_regs = Coils_regs(

# )

Dig_inputs_regs = namedtuple('Dig_inputs_regs',
                        ['TX_CGT_A', 
                         'TX_CGT_B',
                         'TX_CGT_C',
                         'TX_CGT_D',
                         'TX_CMK_A',
                         'TX_CMK_B',
                         'TX_CMK_C',
                         'TX_CMK_D',
                         'TX_V20',
                         'TX_V71',
                         'TX_V74',
                         'TX_V75',
                         'TX_V76',
                         'TX_V77',
                         'TX_V78',
                         'TX_V79',
                         'TX_V80',
                         'TX_V81',
                         'TX_V82',
                         'TX_V83',
                         'TX_IP_A',
                         'TX_IP_B',
                         'TX_IP_C',
                         'TX_IP_D',
                         'TX_ALC',
                         'TX_AX',
                         'TX_GS1',
                         'TX_GS5',
                         'TX_GS20',
                         'TX_GS21',
                         'TX_GS29',
                         'TX_GS30',
                         'TX_IST',
                         'TX_MOF',
                         'TX_MON',
                         'TX_PDB',
                         'TX_RCLP',
                         'TX_V42',
                         'TX_ALM',
                         'TX_EO',
                         'TX_V15',
                         'TX_V44',
                         'TX_V46',
                         'TX_EX',
                         'TX_MST',
                         'TX_SASTAT',
                         'TX_V50'])

dig_inputs_regs = Dig_inputs_regs(
    TX_CGT_A=761, 
    TX_CGT_B=769,
    TX_CGT_C=777, 
    TX_CGT_D=785,
    TX_CMK_A=793, 
    TX_CMK_B=801,
    TX_CMK_C=809, 
    TX_CMK_D=817,
    TX_V20=825,
    TX_V71=857,
    TX_V74=889,
    TX_V75=921,
    TX_V76=953,
    TX_V77=985,
    TX_V78=1017,
    TX_V79=1049,
    TX_V80=1081,
    TX_V81=1113,
    TX_V82=1145,
    TX_V83=1177,
    TX_IP_A=1209,
    TX_IP_B=1217,
    TX_IP_C=1225,
    TX_IP_D=1233,
    TX_ALC=1241,
    TX_AX=1242,
    TX_GS1=1243,
    TX_GS5=1244,
    TX_GS20=1245,
    TX_GS21=1246,
    TX_GS29=1247,
    TX_GS30=1248,
    TX_IST=1249,
    TX_MOF=1250,
    TX_MON=1251,
    TX_PDB=1252,
    TX_RCLP=1253,
    TX_V42=1254,
    TX_ALM=1255,
    TX_EO=1256,
    TX_V15=1257,
    TX_V44=1258,
    TX_V46=1259,
    TX_EX=1260,
    TX_MST=1268,
    TX_SASTAT=1276,
    TX_V50=1284
    ) 
